### ISSUE TITLE
Trying to compile the project locally

### ISSUE THREAD

**Issue by meneguzzi** [stolba/MADLAPlanner#2]
I've been trying to compile the project locally using maven, but I keep running into dependency problems. I tried adding the alive repository to the pom.xml (adding the code below to the repositories section of the pom.xml) to see if it would download these dependencies, but I've had no success. 
```maven
   <repository>
        <id>jones</id>
        <name>jones-releases</name>
        <url>http://jones.felk.cvut.cz/artifactory/pub-release-local</url>
    </repository>
```
Would it be possible to provide additional instructions as to how I could compile the project locally with maven?

**Comment by stolba** [comment]
I have added missing sources and removed unnecessary dependencies, it should work now, please let me know if not

**Comment by meneguzzi** [comment]
Hi,

I just cloned the repository afresh and ran ```mvn test```, but I get the following errors when trying to resolve dependencies locally:
```
mvn test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building MADLA Planner
[INFO]    task-segment: [test]
[INFO] ------------------------------------------------------------------------
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
Downloading: http://clojars.org/repo//cz/agents/alite/alite/1.0-SNAPSHOT/alite-1.0-SNAPSHOT.pom
[INFO] Unable to find resource 'cz.agents.alite:alite:pom:1.0-SNAPSHOT' in repository clojars (http://clojars.org/repo/)
Downloading: http://clojars.org/repo//cz/agents/alite/zeromq/1.0-SNAPSHOT/zeromq-1.0-SNAPSHOT.pom
[INFO] Unable to find resource 'cz.agents.alite:zeromq:pom:1.0-SNAPSHOT' in repository clojars (http://clojars.org/repo/)
Downloading: http://clojars.org/repo//cz/agents/alite/alite/1.0-SNAPSHOT/alite-1.0-SNAPSHOT.jar
[INFO] Unable to find resource 'cz.agents.alite:alite:jar:1.0-SNAPSHOT' in repository clojars (http://clojars.org/repo/)
Downloading: http://clojars.org/repo//cz/agents/alite/zeromq/1.0-SNAPSHOT/zeromq-1.0-SNAPSHOT.jar
[INFO] Unable to find resource 'cz.agents.alite:zeromq:jar:1.0-SNAPSHOT' in repository clojars (http://clojars.org/repo/)
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Missing:
----------
1) cz.agents.alite:alite:jar:1.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=cz.agents.alite -DartifactId=alite -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=cz.agents.alite -DartifactId=alite -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
  	1) cz.agents:madla-planner:jar:1.0-SNAPSHOT
  	2) cz.agents.alite:alite:jar:1.0-SNAPSHOT

2) cz.agents.alite:zeromq:jar:1.0-SNAPSHOT

  Try downloading the file manually from the project website.

  Then, install it using the command:
      mvn install:install-file -DgroupId=cz.agents.alite -DartifactId=zeromq -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there:
      mvn deploy:deploy-file -DgroupId=cz.agents.alite -DartifactId=zeromq -Dversion=1.0-SNAPSHOT -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency:
  	1) cz.agents:madla-planner:jar:1.0-SNAPSHOT
  	2) cz.agents.alite:zeromq:jar:1.0-SNAPSHOT

----------
2 required artifacts are missing.

for artifact:
  cz.agents:madla-planner:jar:1.0-SNAPSHOT

from the specified remote repositories:
  central (http://repo1.maven.org/maven2),
  clojars (http://clojars.org/repo/)



[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 second
[INFO] Finished at: Fri Nov 24 13:17:08 BRST 2017
[INFO] Final Memory: 11M/309M
[INFO] ------------------------------------------------------------------------
```

**Comment by meneguzzi** [comment]
The repository does run the software with the binaries downloaded from the repo, but, while it runs, I get NullPointerExceptions and warnings about actions not assigned to any agents. Specifically:

```
Exception in thread "main" java.lang.NullPointerException
	at cz.agents.dimaptools.input.sas.SASPreprocessor.getProblemForAgent(SASPreprocessor.java:378)
	at cz.agents.madla.creator.ProtobufCreator.initWorld(ProtobufCreator.java:54)
	at cz.agents.madla.creator.SASCreator.createEntities(SASCreator.java:213)
	at cz.agents.madla.creator.SASCreator.create(SASCreator.java:152)
	at cz.agents.alite.Main.main(Main.java:18)
```

**Comment by stolba** [comment]
Hi,

thanks for the report, I'll try to fix that ASAP.
